FROM ubuntu:24.04

LABEL maintainer="kevin@riscv.dev"

# 🧠 Environment setup
ENV DEBIAN_FRONTEND=noninteractive
ENV RISCV=/opt/riscv
ENV CODE_REPO=/opt/repos

# 🧰 Install build dependencies and GDB support libs
RUN apt-get update && apt-get install -y sudo \
  device-tree-compiler autoconf automake autotools-dev curl python3 python3-pip python3-tomli \
  libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo \
  gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake \
  libglib2.0-dev libslirp-dev libx11-dev libxext6 libsm6 libncurses5-dev \
  libusb-1.0-0-dev pkg-config libftdi-dev libgtk-3-dev libpixman-1-dev \
  libreadline-dev libssl-dev python3-pyelftools \
  libpython3-dev libncursesw5-dev libxml2-dev libudev-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# user
ENV USER=ubuntu
ENV HOME=/home/$USER
# 🧑‍💻 Create non-root dev user
RUN id -u $USER >/dev/null 2>&1 || useradd --create-home -s /bin/bash -m $USER \
  && echo "$USER:$USER" | chpasswd \
  && adduser $USER sudo \
  && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
  && chown -R $USER:$USER /home/$USER

WORKDIR $CODE_REPO


# 🧠 Set PATH
ENV PATH="$RISCV_NEWLIB/bin:$RISCV_PK/bin:$RISCV_ISA_SIM/bin:$RISCV_QEMU/bin:/home/$USER/.local/bin:$PATH"


# ⛳ Workspace setup
USER $USER
WORKDIR $HOME
RUN mkdir -p $HOME/workspaces && chown -R $USER:$USER $HOME/workspaces
WORKDIR $HOME/workspaces
RUN echo  "if [ -f $HOME/workspaces/.bash_tmp_rc ]; then" >> ~/.bashrc \
  && echo "    . $HOME/workspaces/.bash_tmp_rc" >> ~/.bashrc \
  && echo "fi" >> ~/.bashrc

#EXPOSE 8080

CMD ["/bin/bash"]